// Optional UI verification. Set PUPPETEER_MODULE to a locally installed Puppeteer ESM entry.
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';

const modulePath = process.env.PUPPETEER_MODULE;
if (!modulePath) throw new Error('Set PUPPETEER_MODULE to a Puppeteer ESM entry to run browser checks.');
const { default: puppeteer } = await import(pathToFileURL(path.resolve(modulePath)).href);
const output = path.resolve('.verification');
const baseUrl = process.env.BASE_URL || 'http://localhost:4317';
await mkdir(output, { recursive: true });
console.log('Launching browser');
const browser = await puppeteer.launch({ headless: true, pipe: true, timeout: 20000 });
const errors = [];
try {
  const page = await browser.newPage();
  console.log('Loading application');
  page.on('pageerror', err => errors.push(err.message));
  await page.setViewport({ width: 1440, height: 1050, deviceScaleFactor: 1 });
  await page.goto(baseUrl, { waitUntil: 'networkidle0' });
  await page.waitForSelector('.character-card');
  console.log('Application rendered');
  await page.evaluate(() => document.fonts.ready);
  assert.equal(await page.$eval('.brand', el => el.textContent.includes('stella')), true);
  assert.equal(await page.$$eval('.character-card', cards => cards.length), 3);
  assert.equal(await page.$$eval('.disc-columns .disc-card', cards => cards.length), 6);
  const defaultNames = await page.$$eval('.character-name h3', nodes => nodes.map(n => n.textContent));
  const brokenImages = await page.$$eval('img', images => images.filter(img => img.complete && !img.naturalWidth).map(img => img.src));
  assert.deepEqual(brokenImages, []);
  await page.evaluate(async () => { for (const img of document.images) img.loading = 'eager'; await Promise.all([...document.images].map(img => img.decode().catch(() => {}))); });
  await page.screenshot({ path: path.join(output, 'desktop.png'), fullPage: true });
  await page.click('[data-action="team"][data-index="1"]');
  const alternateNames = await page.$$eval('.character-name h3', nodes => nodes.map(n => n.textContent));
  assert.notDeepEqual(defaultNames, alternateNames);
  await page.click('[data-action="build-tab"][data-index="1"]');
  assert.equal(await page.$eval('.build-tabs .active', el => el.textContent.includes('Support Trekker')), true);
  await page.click('[data-action="save"]');
  await page.reload({ waitUntil: 'networkidle0' });
  assert.equal(await page.$eval('.saved-button .count', el => el.textContent), '1');
  await page.click('[data-action="saved"]');
  await page.waitForSelector('dialog[open] .saved-entry');
  await page.click('[data-action="load-saved"]');
  assert.deepEqual(await page.$$eval('.character-name h3', nodes => nodes.map(n => n.textContent)), alternateNames);
  await page.click('[data-action="disc-detail"]');
  await page.waitForSelector('dialog[open] .disc-detail');
  assert.equal(await page.$eval('.disc-detail', el => el.textContent.includes('Alasan dipilih')), true);
  await page.keyboard.press('Escape');
  await page.click('[data-action="mode"][data-value="collection"]');
  await page.waitForSelector('.empty-state');
  await page.click('.empty-state [data-action="collection"]');
  await page.waitForSelector('#dialog-catalog');
  for (const id of ['chitose', 'teresa', 'iris']) await page.click(`[data-action="toggle-owned"][data-id="${id}"]`);
  await page.click('[data-action="catalog-kind"][data-value="discs"]');
  await page.select('#catalog-element', 'Aqua');
  const availableDiscs = await page.$$eval('.collection-card', nodes => nodes.map(n => n.dataset.id));
  for (const id of availableDiscs.slice(0, 4)) await page.click(`[data-action="toggle-owned"][data-id="${id}"]`);
  await page.click('[data-action="apply-collection"]');
  const ownedNames = await page.$$eval('.character-name h3', nodes => nodes.map(n => n.textContent));
  assert.deepEqual(ownedNames.slice().sort(), ['Chitose', 'Iris', 'Teresa']);
  assert.equal(await page.$$eval('.disc-columns .disc-card', cards => cards.length), 4);
  await page.reload({ waitUntil: 'networkidle0' });
  assert.deepEqual(await page.$$eval('.character-name h3', nodes => nodes.map(n => n.textContent).sort()), ['Chitose', 'Iris', 'Teresa']);
  await page.click('[data-action="nav"][data-page="trekkers"]');
  await page.type('#catalog-search', 'chitose');
  assert.equal(await page.$$eval('.collection-card', nodes => nodes.length), 1);
  await page.click('[data-action="nav"][data-page="guide"]');
  assert.equal(await page.$eval('.method-panel', el => el.textContent.includes('simulasi DPS')), true);
  await page.click('footer [data-action="nav"][data-page="sources"]');
  assert.equal(await page.$$eval('.source-card', cards => cards.length >= 5), true);
  assert.equal(await page.$eval('.source-grid', el => el.textContent.includes('YouTube')), true);
  await page.screenshot({ path: path.join(output, 'sources.png'), fullPage: true });
  await page.click('[data-action="nav"][data-page="builder"]');
  await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1 });
  await page.screenshot({ path: path.join(output, 'mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No mobile horizontal overflow');
  await page.click('[data-action="collection"]');
  await page.waitForSelector('dialog[open] .collection-card');
  assert.equal(await page.evaluate(() => document.querySelector('dialog').scrollWidth <= document.querySelector('dialog').clientWidth), true, 'No dialog horizontal overflow');
  await page.screenshot({ path: path.join(output, 'mobile-collection.png'), fullPage: false });
  await page.keyboard.press('Escape');
  await page.setViewport({ width: 320, height: 720, deviceScaleFactor: 1 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No narrow mobile overflow');
  assert.deepEqual(errors, [], 'No browser runtime errors');
  const report = { passed: true, defaultNames, alternateNames, collectionNames: ownedNames, collectionDiscs: 4, runtimeErrors: errors, screenshots: ['desktop.png', 'mobile.png', 'mobile-collection.png'] };
  await writeFile(path.join(output, 'browser-report.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); }
