// Game facts were checked against StellaBase's public game-data records.
// Tags, priorities, and suggested potential routes are editorial annotations.
const SOURCE = 'https://stella.ennead.cc';

// The names below were checked against mainCore/supportCore in each record.
// Separate routes prevent main-position priorities leaking into support builds.
const MAIN_VARIANTS = {
  nazuka: {
    focus: 'Main DPS · pinwheel Skill',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Ventus DMG', 'ATK'],
    potentials: ['Blooming Gale', 'Everlasting Elegance'],
    skills: ['Main Skill: Blooming Draught', 'Ultimate: Aromatic Tempest'],
    tip: 'Perpanjang durasi pinwheel dan jaga channel Main Skill. Pasangkan dengan pemasang Breeze; jalur main ini memicu Mark lewat pinwheel.',
  },
  freesia: {
    focus: 'Main DPS · charged Whirlwind Slash',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Aqua DMG', 'ATK'],
    potentials: ['Whirlwind Frenzy', 'Unstoppable March'],
    skills: ['Main Skill: Freezing Swirl', 'Ultimate: Elegy of Frost'],
    tip: 'Tahan Main Skill untuk memperpanjang serangan. Jalur Whirlwind memperkuat channel; butuh pemasang Aqua Mark seperti Iris atau Teresa.',
  },
  iris: {
    focus: 'Main DPS · Glacier Greatarrow',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Aqua DMG', 'ATK'],
    potentials: ['Vector: Solidifying', 'Vector: Shatter'],
    skills: ['Main Skill: Frozen Path', 'Ultimate: Arctic Vortex'],
    tip: 'Bangun tumpukan lewat Auto Attack sebelum Main Skill. Cabang Vector memperkuat Greatarrow; efek Glacier Array dari jalur support tidak berlaku di posisi ini.',
  },
  ridge: {
    focus: 'Main DPS · energy rounds',
    damageTags: ['basic', 'mark'], stats: ['Auto Attack DMG', 'Terra DMG', 'ATK'],
    potentials: ['A Fortunate Yield', 'Tangled Mess'],
    skills: ['Main Skill: Bean Cyclone', 'Ultimate: Harvest Rhapsody'],
    tip: 'Gunakan Main Skill untuk reload dan memperkuat Auto Attack. Jalur ini membangun energy rounds; sediakan Earth Vein dari support Terra.',
  },
  chixia: {
    focus: 'Main DPS · torrent of flames',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Ignis DMG', 'ATK'],
    potentials: ['Sleepless Flame', 'Blazing Rainbow Array'],
    skills: ['Main Skill: Purifying Flames', "Ultimate: Dragon's Ascension"],
    tip: 'Jaga musuh dalam jangkauan semburan api. Jalur main memakai Skill DMG; prioritas Minion DMG dari build Crimson Dragon support tidak dipakai di sini.',
  },
  minova: {
    focus: 'Main DPS · combo base hit',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Lux DMG', 'ATK'],
    potentials: ['Ultimatum', 'Clan Clash Artistry'],
    skills: ['Main Skill: Syou: Pulsar Streak', 'Ultimate: Ketsu: Entropic Convergence'],
    tip: 'Lanjutkan rangkaian Base Hit dan sediakan Radiance dari support Lux. Shield Oath Satellite adalah potential support dan tidak menjadi bagian jalur main ini.',
  },
  mistique: {
    focus: 'Main DPS · Pumpka Phantom',
    damageTags: ['minion', 'mark'], stats: ['Minion DMG', 'Umbra DMG', 'ATK'],
    potentials: ['Extended Exposure', 'Thread the Needle'],
    skills: ['Main Skill: Pumpka Pummel', 'Ultimate: Midnight ★ Terror'],
    tip: 'Jaga Exposure dan jumlah Pumpka Phantom. Pasang Gloom lewat support seperti Cosette; build main memanggil Pumpka, sedangkan jalur support memakai Lanterna.',
  },
};

const SUPPORT_VARIANTS = {
  nanoha: {
    focus: 'Support DPS · exploding sunflower',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Ventus DMG', 'ATK'],
    potentials: ['Floral Nexus', 'Gentle Thaw'],
    skills: ['Support Skill: Flowers Bloom', 'Ultimate: Flowers Thrice'],
    tip: 'Bunga support memicu Ventus Mark; sediakan pemasang Breeze lain. Floral Nexus membantu shuriken mengikuti target dan Gentle Thaw memberi manfaat saat Mark dipicu.',
  },
  noya: {
    focus: 'Support DPS · sword aura',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Ventus DMG', 'ATK'],
    potentials: ['Gallop: Flurry!', 'Gallop: Squall!'],
    skills: ['Support Skill: Gale Storm', 'Ultimate: Skyshatter Rend'],
    tip: 'Bangun major sword aura pada cabang Gallop. Noya support memicu Breeze; ia tetap membutuhkan pemasang Mark di tim.',
  },
  chitose: {
    focus: 'Support DPS · rapid combo slash',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Crit Rate', 'Aqua DMG'],
    potentials: ['Submerged Fang', 'Whirl Blade'],
    skills: ['Support Skill: Water Surge', 'Ultimate: Waves of Naraka'],
    tip: 'Cabang ini memperkuat rapid combo slash. Whirl Blade mendapat manfaat dari Crit; tetap sediakan pemasang Aqua Mark untuk dipicu.',
  },
  shimiao: {
    focus: 'Support DPS · water blades',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Aqua DMG', 'ATK'],
    potentials: ['Rain Whisper: Gentle', 'Rain Whisper: Light'],
    skills: ['Support Skill: Aqua Aide', 'Ultimate: Flood Mantra'],
    tip: 'Bangun jumlah water blade dan durasi kontribusinya lewat jalur Rain Whisper. Support Skill dapat memicu Torrent dari rekan Aqua.',
  },
  chaton: {
    focus: 'Support DPS · Penetrating Bullet',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Ignis DMG', 'ATK'],
    potentials: ['Ambush Operation', 'Combat Frenzy'],
    skills: ['Support Skill: Blitz Assault', 'Ultimate: Dark Evil Eye'],
    tip: 'Cabang support membangun tembakan Penetrating Bullet. Potential Bouncing Bomb milik Main Skill tidak menjadi prioritas di posisi ini.',
  },
  amber: {
    focus: 'Support DPS · Bullet Waltz',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Ignis DMG', 'ATK'],
    potentials: ['Hunting Waltz', 'Scattering Waltz'],
    skills: ['Support Skill: Bullet Waltz', 'Ultimate: Spark of Finality'],
    tip: 'Bangun serangan dan Shadows dari Bullet Waltz. Jalur support memakai Skill DMG; prioritas magazine Auto Attack adalah untuk Amber main.',
  },
  gerie: {
    focus: 'Support DPS · chained spades',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Terra DMG', 'ATK'],
    potentials: ['Deeper into Sin', 'Curtain Call'],
    skills: ['Support Skill: Immediate Execution', 'Ultimate: Divine: Retribution of Evil'],
    tip: 'Perkuat chained spades dan serangan saat spade ditarik. Build support ini memakai Skill DMG, sementara Lethal Auto Attack adalah jalur main.',
  },
  shia: {
    focus: 'Support DPS · surfing attacks',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Lux DMG', 'ATK'],
    potentials: ['Bunny Torrent', 'Rabbit Flip'],
    skills: ['Support Skill: Surfing Rondo', 'Ultimate: Divine Deluge'],
    tip: 'Tambahkan jumlah surfing dan area bermuatan melalui cabang support. Sediakan Lux Mark agar serangan Shia dapat memicunya.',
  },
  laru: {
    focus: 'Support DPS · Thunder Domain',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Lux DMG', 'ATK'],
    potentials: ['Radiant Flame: Cycle Restart', 'Radiant Flame: Flash Point'],
    skills: ['Support Skill: Divine Thunderquake', 'Ultimate: Thunderfall Thrust'],
    tip: 'Jalur support menambah jumlah Thunder Domain dan damage berulangnya. Pasangkan dengan pemasang Radiance seperti Tilia.',
  },
  firenze: {
    focus: 'Support DPS · Shadow Clone',
    damageTags: ['minion', 'mark'], stats: ['Minion DMG', 'Umbra DMG', 'ATK'],
    potentials: ['Twin Shadow', 'Shadownight Descendant'],
    skills: ['Support Skill: Reign of Night', 'Ultimate: Personal Tuition'],
    tip: 'Tambah jumlah dan durasi Shadow Clone dari Reign of Night. Serangan main Trekker memicu serangan lanjutan clone support.',
  },
  caramel: {
    focus: 'Support DPS · bass sweep',
    damageTags: ['skill', 'mark'], stats: ['Skill DMG', 'Umbra DMG', 'ATK'],
    potentials: ['Melody Return', 'Heavenly Dropbeat'],
    skills: ['Support Skill: Melodic Sweep', 'Ultimate: Melodic Seraphim'],
    tip: 'Fokuskan potential pada sapuan Support Skill. Build Auto Attack di dekat Demonic Boombox adalah jalur Caramel pada posisi main.',
  },
};

function trekker({ sourceId, focus, stats, potentials, skills, tip, ...data }) {
  const buildPosition = data.role === 'Vanguard' ? 'main' : 'support';
  const build = { focus, stats, potentials, skills, tip, damageTags: data.damageTags };
  const builds = { [buildPosition]: build };
  if (MAIN_VARIANTS[data.id]) builds.main = MAIN_VARIANTS[data.id];
  if (SUPPORT_VARIANTS[data.id]) builds.support = SUPPORT_VARIANTS[data.id];
  return {
    ...data,
    image: `/images/${data.id}.png`,
    source: `${SOURCE}/trekkers/${sourceId}`,
    buildPosition,
    builds,
    build,
  };
}

export const TREKKERS = [
  trekker({
    id: 'nanoha', sourceId: 119, name: 'Nanoha', element: 'Ventus', role: 'Vanguard', rarity: 5,
    damageTags: ['skill', 'mark', 'ultimate'], supportTags: [],
    summary: 'Shuriken berulang memicu Ventus Mark. Clone dari Ultimate menambah serangan selama durasinya.',
    focus: 'Main DPS · shuriken Skill', stats: ['Skill DMG', 'Ventus DMG', 'ATK'],
    potentials: ['Whirling Blade', 'Bloom Dance'],
    skills: ['Main Skill: Flowers Dance', 'Ultimate: Flowers Thrice'],
    tip: 'Pasangkan dengan pemasang Ventus Mark seperti Nazuka atau Ann. Jalur ini memusatkan investasi pada shuriken Main Skill.',
  }),
  trekker({
    id: 'nazuka', sourceId: 133, name: 'Nazuka', element: 'Ventus', role: 'Versatile', rarity: 5,
    damageTags: ['skill'], supportTags: ['mark'],
    summary: 'Bouquet dan Flower Formation memasang Ventus Mark untuk serangan rekan satu elemen.',
    focus: 'Support DPS · aplikasi Mark', stats: ['Skill DMG', 'Ventus DMG', 'ATK'],
    potentials: ['Youth: Dazzling', 'Youth: Hunting'],
    skills: ['Support Skill: Bouquet Blast', 'Ultimate: Aromatic Tempest'],
    tip: 'Utamakan uptime Flower Petals. Jalur support ini menyuplai Mark agar Vanguard Ventus dapat terus memicunya.',
  }),
  trekker({
    id: 'ann', sourceId: 123, name: 'Ann', element: 'Ventus', role: 'Support', rarity: 4,
    damageTags: ['skill'], supportTags: ['mark', 'buff', 'shield', 'debuff'],
    summary: 'Dinding angin menahan proyektil dan memasang Ventus Mark. Potential tertentu memberi shield serta buff ATK.',
    focus: 'Support · perlindungan dan Mark', stats: ['HP', 'ATK', 'Ventus DMG'],
    potentials: ['Warm Wind Guard', 'Wind Banish'],
    skills: ['Support Skill: Wind Barrier', 'Ultimate: Call of the Wild'],
    tip: 'Dengan Warm Wind Guard, lewati dinding angin untuk memperoleh shield dan buff. HP memperkuat shield yang berskala dari HP dasar Ann.',
  }),
  trekker({
    id: 'noya', sourceId: 112, name: 'Noya', element: 'Ventus', role: 'Vanguard', rarity: 4,
    damageTags: ['skill', 'mark'], supportTags: [],
    summary: 'Tebasan beruntun memicu Breeze menjadi Cyclone. Pilihan Vanguard Ventus bintang empat.',
    focus: 'Main DPS · combo Skill', stats: ['Skill DMG', 'Ventus DMG', 'ATK'],
    potentials: ['Slash: Dual Strike!', 'Slash: Chain Slash!'],
    skills: ['Main Skill: Sonic Slash', 'Ultimate: Skyshatter Rend'],
    tip: 'Sediakan Breeze dari support sebelum combo. Fokuskan potential pada cabang Skill agar investasi damage tetap konsisten.',
  }),
  trekker({
    id: 'chitose', sourceId: 144, name: 'Chitose', element: 'Aqua', role: 'Vanguard', rarity: 5,
    damageTags: ['skill', 'mark'], supportTags: [],
    summary: 'Dash berulang membuka Torrent Flash yang diperkuat dan memicu Aqua Mark.',
    focus: 'Main DPS · Torrent Flash', stats: ['Skill DMG', 'Aqua DMG', 'ATK'],
    potentials: ['Cascade of Ruin', 'Against the Flow'],
    skills: ['Main Skill: Torrent Flash', 'Ultimate: Waves of Naraka'],
    tip: 'Jaga siklus Main Skill dan ketersediaan Aqua Mark. Shield Teresa membantu mempertahankan tekanan saat bertarung jarak dekat.',
  }),
  trekker({
    id: 'freesia', sourceId: 125, name: 'Freesia', element: 'Aqua', role: 'Versatile', rarity: 5,
    damageTags: ['skill'], supportTags: ['mark'],
    summary: 'Ice Flowers memasang Torrent. Saat Berserk, Freesia dapat terus menyerang meski berada di posisi support.',
    focus: 'Support DPS · Ice Flowers', stats: ['Skill DMG', 'Aqua DMG', 'ATK'],
    potentials: ['Realm of Frost', 'Chill Forecast'],
    skills: ['Support Skill: Frost Bloom', 'Ultimate: Elegy of Frost'],
    tip: 'Bangun cakupan Ice Flowers dan gunakan Ultimate agar Freesia menyerang sebagai support selama Berserk.',
  }),
  trekker({
    id: 'teresa', sourceId: 127, name: 'Teresa', element: 'Aqua', role: 'Support', rarity: 4,
    damageTags: ['skill'], supportTags: ['shield', 'mark', 'buff'],
    summary: 'Tidal Domain memberikan Surging Shield kepada main Trekker, sekaligus memasang Aqua Mark.',
    focus: 'Support · Surging Shield', stats: ['ATK', 'Aqua DMG', 'Skill DMG'],
    potentials: ['Surge: Infinite', 'Surge: Ripple'],
    skills: ['Support Skill: Billowing Tide', 'Ultimate: Slicing Riptide'],
    tip: 'Surging Shield berskala dari ATK dasar Teresa. Perpanjang durasinya untuk menjaga perlindungan dan pasokan Mark bagi main Trekker Aqua.',
  }),
  trekker({
    id: 'iris', sourceId: 111, name: 'Iris', element: 'Aqua', role: 'Versatile', rarity: 4,
    damageTags: ['skill'], supportTags: ['mark', 'gather'],
    summary: 'Glacier Array menyerang area dan memasang Torrent. Potential Vortex menambahkan tarikan musuh.',
    focus: 'Support DPS · area dan kontrol', stats: ['Skill DMG', 'Aqua DMG', 'ATK'],
    potentials: ['Blizzard: Spread', 'Blizzard: Vortex'],
    skills: ['Support Skill: Iceberg Surge', 'Ultimate: Arctic Vortex'],
    tip: 'Pilihan bintang empat untuk menyuplai Aqua Mark. Tarikan Blizzard: Vortex membantu serangan area mengenai lebih banyak musuh.',
  }),
  trekker({
    id: 'shimiao', sourceId: 113, name: 'Shimiao', element: 'Aqua', role: 'Vanguard', rarity: 4,
    damageTags: ['skill', 'mark'], supportTags: [],
    summary: 'Main Skill dua fase memicu Torrent; cabang potential dapat menguatkan serangan terhadap elite.',
    focus: 'Main DPS · Skill melawan elite', stats: ['Skill DMG', 'Aqua DMG', 'ATK'],
    potentials: ['Stream Embrace', 'Wave Swirl'],
    skills: ['Main Skill: Rising Tides', 'Ultimate: Flood Mantra'],
    tip: 'Sediakan Torrent dari Iris atau Teresa. Untuk gerombolan, pertimbangkan cabang Torrent Plunge sesuai pilihan potential yang muncul.',
  }),
  trekker({
    id: 'chaton', sourceId: 114, name: 'Chaton', element: 'Ignis', role: 'Vanguard', rarity: 5,
    damageTags: ['skill', 'ultimate', 'mark'], supportTags: [],
    summary: 'Main Skill memiliki mode laser dan bom. Ultimate membuka Evil Eye Unleashed dengan serangan yang diperkuat.',
    focus: 'Main DPS · Bouncing Bomb', stats: ['Skill DMG', 'Ignis DMG', 'ATK'],
    potentials: ['Area Explosion', 'Overwhelming Throw'],
    skills: ['Main Skill: Sniper Operation', 'Ultimate: Dark Evil Eye'],
    tip: 'Tahan Main Skill untuk cabang Bouncing Bomb ini. Chixia atau Flora memasang Ignis Mark untuk dipicu oleh Chaton.',
  }),
  trekker({
    id: 'chixia', sourceId: 141, name: 'Chixia', element: 'Ignis', role: 'Versatile', rarity: 5,
    damageTags: ['minion', 'skill'], supportTags: ['mark'],
    summary: 'Support Skill memanggil Crimson Dragon. Serangan minion memasang Sacred Flame untuk Vanguard Ignis.',
    focus: 'Support DPS · Crimson Dragon', stats: ['Minion DMG', 'Ignis DMG', 'ATK'],
    potentials: ['Crimson Dragon: Convergence', 'Crimson Dragon: Chant'],
    skills: ['Support Skill: Awakening: Crimson Dragon', "Ultimate: Dragon's Ascension"],
    tip: 'Bangun jumlah dan uptime naga. Bedakan bonus Minion DMG dengan Skill DMG saat memilih Disc.',
  }),
  trekker({
    id: 'flora', sourceId: 126, name: 'Flora', element: 'Ignis', role: 'Support', rarity: 4,
    damageTags: ['skill'], supportTags: ['buff', 'mark', 'heal', 'gather'],
    summary: 'Butterfly memberi buff kritikal dan Sacred Flame. Backstage Support dapat memulihkan HP saat rekan menghasilkan Crit.',
    focus: 'Support · buff kritikal', stats: ['ATK', 'Ignis DMG', 'Skill DMG'],
    potentials: ['Ashes of the Past', 'Spark of Ashes', 'Backstage Support'],
    skills: ['Support Skill: Flutter Flare', 'Ultimate: Undying Phoenix'],
    tip: 'Prioritaskan Butterfly sebelum burst Vanguard. Pemulihan HP membutuhkan Backstage Support dan pemicu Crit dari rekan; bukan heal tanpa syarat.',
  }),
  trekker({
    id: 'amber', sourceId: 103, name: 'Amber', element: 'Ignis', role: 'Vanguard', rarity: 4,
    damageTags: ['basic', 'mark'], supportTags: [],
    summary: 'Main Skill memperkuat Auto Attack. Potential magazine membuka rangkaian tembakan setelah reload.',
    focus: 'Main DPS · Auto Attack', stats: ['Auto Attack DMG', 'ATK SPD', 'ATK'],
    potentials: ['Dominant Firepower', 'Bullet Storm'],
    skills: ['Main Skill: Fireworks Jam', 'Ultimate: Spark of Finality'],
    tip: 'Gunakan Main Skill sebelum menghabiskan magazine. Buff kritikal Flora mendukung tembakan berulang Amber.',
  }),
  trekker({
    id: 'gerie', sourceId: 149, name: 'Gerie', element: 'Terra', role: 'Vanguard', rarity: 5,
    damageTags: ['basic', 'mark'], supportTags: [],
    summary: 'Iron Cage mengaktifkan Lethal dan meningkatkan Auto Attack. Cabang potential memperluas serangan serta pemicu Terra Mark.',
    focus: 'Main DPS · Lethal Auto Attack', stats: ['Auto Attack DMG', 'Terra DMG', 'ATK'],
    potentials: ['Beyond All Control', 'Avalanche of Stone'],
    skills: ['Main Skill: Thorned Inferno', 'Ultimate: Divine: Retribution of Evil'],
    tip: 'Jaga Lethal aktif dan sediakan Terra Mark dari Ridge atau Nazuna. Beyond All Control membantu saat harus meninggalkan Iron Cage.',
  }),
  trekker({
    id: 'ridge', sourceId: 116, name: 'Ridge', element: 'Terra', role: 'Versatile', rarity: 4,
    damageTags: ['skill', 'mark'], supportTags: ['mark'],
    summary: 'Seed shower memasang Earth Vein dan Seed Orb. Pemicu Terra Mark dari rekan mengaktifkan damage tambahan.',
    focus: 'Support DPS · Seed Orb', stats: ['Skill DMG', 'Terra DMG', 'ATK'],
    potentials: ['Hasty Growth', 'Misplaced Bloom'],
    skills: ['Support Skill: Floral Storm', 'Ultimate: Harvest Rhapsody'],
    tip: 'Pasangkan dengan pemicu Terra Mark. Perpanjangan Seed Orb membantu menjaga rangkaian ledakan selama Vanguard menyerang.',
  }),
  trekker({
    id: 'nazuna', sourceId: 156, name: 'Nazuna', element: 'Terra', role: 'Support', rarity: 5,
    damageTags: ['skill'], supportTags: ['buff', 'heal', 'mark'],
    summary: 'Hasil raffle memberi buff ATK atau Terra DMG. Hasil seluruhnya hati memulihkan HP main Trekker.',
    focus: 'Support · Heart dan pemulihan', stats: ['ATK', 'Terra DMG', 'Skill DMG'],
    potentials: ['Arrow of Affection', 'Sweetheart Bloom', 'Honeyed Arrow'],
    skills: ['Support Skill: Bingo Crush', 'Ultimate: Dream Spiral'],
    tip: 'Cabang Heart meningkatkan peluang hasil hati. Heal tetap bergantung pada hasil raffle; sesuaikan permainan dengan HP yang tersedia.',
  }),
  trekker({
    id: 'shia', sourceId: 155, name: 'Shia', element: 'Lux', role: 'Vanguard', rarity: 5,
    damageTags: ['skill', 'mark'], supportTags: [],
    summary: 'Drone Main Skill menyerang berulang dan memicu Lux Mark. Cabang Rabbit mengembangkan damage dari serangan tersebut.',
    focus: 'Main DPS · drone Skill', stats: ['Skill DMG', 'Lux DMG', 'ATK'],
    potentials: ['Rimecrystal Edge', 'Astral Pirouette'],
    skills: ['Main Skill: Whirling Waves', 'Ultimate: Divine Deluge'],
    tip: 'Jalur ini memilih Rabbit yang dipanggil Main Skill. Periksa tipe damage pada potential; drone tidak otomatis berarti Minion DMG.',
  }),
  trekker({
    id: 'minova', sourceId: 132, name: 'Minova', element: 'Lux', role: 'Versatile', rarity: 5,
    damageTags: ['skill'], supportTags: ['mark', 'buff', 'shield'],
    summary: 'Astral Hex memasang Radiance. Potential support dapat memberi shield dan Meteor yang meningkatkan ATK saat diambil.',
    focus: 'Support DPS · Astral Hex', stats: ['Skill DMG', 'Lux DMG', 'ATK'],
    potentials: ['Oath Satellite', 'Star Core Crumbled'],
    skills: ['Support Skill: Gi: Supernova Burst', 'Ultimate: Ketsu: Entropic Convergence'],
    tip: 'Ambil Meteor yang dihasilkan Star Core Crumbled untuk buff ATK. Shield membutuhkan potential Oath Satellite.',
  }),
  trekker({
    id: 'tilia', sourceId: 107, name: 'Tilia', element: 'Lux', role: 'Support', rarity: 4,
    damageTags: ['skill'], supportTags: ['mark', 'buff', 'debuff', 'shield', 'skill'],
    summary: 'Aegis memasang Radiance dan stun. Potential Lux sphere menambah kerentanan musuh; Chalk Armor memberi shield saat Ultimate mengenai target.',
    focus: 'Support · Radiance dan perlindungan', stats: ['HP', 'ATK', 'Lux DMG'],
    potentials: ['Holy Inscription', 'Knight Oath: Chalk Armor'],
    skills: ['Support Skill: Aegis Intervention', 'Ultimate: Glorious Smite'],
    tip: 'Pilih Chalk Armor jika tim memerlukan shield. HP memperkuat shield tersebut; Holy Inscription meningkatkan manfaat tim Lux dari Aegis.',
  }),
  trekker({
    id: 'laru', sourceId: 150, name: 'Laru', element: 'Lux', role: 'Vanguard', rarity: 4,
    damageTags: ['skill', 'mark'], supportTags: [],
    summary: 'Sapuan dan laser memicu Radiance menjadi Thunderbolt. Potential menambah Thunder Domain dan serangan ke target Shock.',
    focus: 'Main DPS · laser dan Thunder Domain', stats: ['Skill DMG', 'Lux DMG', 'ATK'],
    potentials: ['Aerial Suspension', 'Arc Chain Laser'],
    skills: ['Main Skill: Thunderflare Strike', 'Ultimate: Thunderfall Thrust'],
    tip: 'Tilia dan Minova dapat memasok Radiance. Pertahankan target dalam jangkauan Thunder Domain untuk mendapatkan manfaat damage berulang.',
  }),
  trekker({
    id: 'firenze', sourceId: 110, name: 'Firenze', element: 'Umbra', role: 'Vanguard', rarity: 5,
    damageTags: ['minion', 'mark'], supportTags: [],
    summary: 'Memanggil Shadow Clone yang melakukan combo. Clone memicu Umbra Mark dan mendapat jalur ledakan saat menghilang.',
    focus: 'Main DPS · Shadow Clone', stats: ['Minion DMG', 'Umbra DMG', 'ATK'],
    potentials: ['Phantom Waltz', 'Shadow Step'],
    skills: ['Main Skill: Elegant Parade', 'Ultimate: Personal Tuition'],
    tip: 'Shadow Step meningkatkan batas clone berdasarkan rekan Umbra. Mistique dan Cosette memasok Gloom untuk rangkaian pemicu Mark.',
  }),
  trekker({
    id: 'mistique', sourceId: 135, name: 'Mistique', element: 'Umbra', role: 'Versatile', rarity: 5,
    damageTags: ['minion'], supportTags: ['mark', 'gather'],
    summary: 'Summoning Circle menghasilkan Lanterna Phantom yang meledak dan memasang Gloom. Potential tertentu menarik musuh ke lingkaran.',
    focus: 'Support DPS · Lanterna Phantom', stats: ['Minion DMG', 'Umbra DMG', 'ATK'],
    potentials: ['Happy Face', 'Slumber Invitation'],
    skills: ['Support Skill: Summoning Circle', 'Ultimate: Midnight ★ Terror'],
    tip: 'Jaga musuh di dalam lingkaran agar ledakan phantom konsisten. Tarikan memerlukan Slumber Invitation.',
  }),
  trekker({
    id: 'cosette', sourceId: 142, name: 'Cosette', element: 'Umbra', role: 'Support', rarity: 4,
    damageTags: ['skill'], supportTags: ['mark', 'debuff', 'gather'],
    summary: 'Claw strike memasang Gloom dan meningkatkan Umbra DMG yang diterima musuh. Ultimate menarik musuh ke area serangan.',
    focus: 'Support · debuff Umbra', stats: ['ATK', 'Umbra DMG', 'Skill DMG'],
    potentials: ['Abyssal Mark', 'Eclipse Imprint'],
    skills: ['Support Skill: Abyssal Hunter', 'Ultimate: Dark Apocalypse'],
    tip: 'Gunakan debuff sebelum burst rekan Umbra. Pengumpulan musuh memberi ruang bagi phantom Mistique dan clone Firenze untuk menyerang bersama.',
  }),
  trekker({
    id: 'caramel', sourceId: 147, name: 'Caramel', element: 'Umbra', role: 'Vanguard', rarity: 4,
    damageTags: ['basic', 'mark'], supportTags: [],
    summary: 'Demonic Boombox memicu Gloom dan memberi buff ATK saat Caramel berada di dekatnya.',
    focus: 'Main DPS · Auto Attack finale', stats: ['Auto Attack DMG', 'Umbra DMG', 'ATK'],
    potentials: ['Baseline Finale', 'Cheer Sparkle'],
    skills: ['Main Skill: Co-Performance', 'Ultimate: Melodic Seraphim'],
    tip: 'Bertarung di dekat Boombox untuk mempertahankan buff. Pasokan Gloom membantu cabang Auto Attack finale ini.',
  }),
];

function disc(sourceId, name, element, rarity, tags, summary, notes) {
  return { id: `disc-${sourceId}`, name, element, rarity, tags, summary, notes,
    ...(sourceId === 211004 ? { effectTarget: 'support' } : [211001, 211003].includes(sourceId) ? { effectTarget: 'main' } : {}),
    image: `/images/disc-${sourceId}.png`, source: `${SOURCE}/discs/${sourceId}` };
}

const skillDisc = (id, name, element) => disc(id, name, element, 4, ['skill', 'buff'],
  `Menaikkan Skill DMG ${element}; bonus hit tambahan bergantung pada HP main Trekker.`,
  `Harmony menguatkan Skill main ${element} ketika support ${element} berada di medan. Periksa ambang HP dan kebutuhan Note.`);

const ultimateDisc = (id, name, element) => disc(id, name, element, 4, ['ultimate', 'buff', 'minion'],
  `Menaikkan ATK ${element}; penggunaan Skill memberi buff Ultimate DMG sementara.`,
  `Harmony memberi ATK untuk Trekker dan minion ${element} setelah Mark elemen tersebut dipicu. Memerlukan Note yang sesuai.`);

const elementDisc = (id, name, element) => disc(id, name, element, 3, ['buff'],
  `Menaikkan damage ${element} tim.`, 'Tanpa Harmony. Opsi sederhana saat koleksi Disc masih terbatas.');

export const DISCS = [
  disc(214028, 'Daylight Garden', 'Ventus', 5, ['basic', 'skill', 'ultimate', 'debuff'],
    'Menaikkan Auto Attack dan Skill main Ventus; pemicu Ventus Mark menambah damage elemennya.',
    'Harmony menambah manfaat Ultimate dan serangan berulang ke target yang sama. Memerlukan Note yang sesuai.'),
  disc(214002, 'Sky, Flowers, Poem', 'Ventus', 5, ['ultimate', 'debuff', 'buff'],
    'Menaikkan Ventus DMG. Damage selain Auto Attack berpeluang memberi Laceration, meningkatkan damage Ventus yang diterima target.',
    'Harmony menguatkan Ultimate pada target Laceration; bonus lain dipicu saat target Laceration dikalahkan.'),
  disc(214001, 'Meowing Cat God', 'Ignis', 5, ['ultimate', 'buff', 'minion'],
    'Menaikkan Ignis DMG. Main Ignis yang memakai Skill memberi ATK tim dan minion serta memperoleh pengurangan damage.',
    'Harmony menguatkan Ultimate melawan elite selama Blazing Armor aktif. Pengurangan damage bukan shield HP.'),
  disc(214005, 'Sunlit Blossom', 'Aqua', 5, ['basic', 'skill', 'buff'],
    'Menaikkan Aqua DMG, dengan bonus tambahan melawan target Chill atau Frozen.',
    'Harmony memberi bonus Auto Attack dan Skill setelah Ultimate Aqua, serta bonus Skill saat support Aqua berada di medan.'),
  disc(214006, "Witch's Swing", 'Umbra', 5, ['minion', 'ultimate', 'buff'],
    'Menaikkan damage Umbra unit sekutu; Support Skill Umbra meningkatkan efek ini untuk sementara.',
    'Harmony mendukung ATK, minion, dan Ultimate melalui summon serta pemicu Umbra Mark. Periksa kebutuhan Note.'),
  disc(214007, 'Midnight Mayhem', 'Lux', 5, ['skill', 'ultimate', 'basic', 'debuff'],
    'Menaikkan Skill dan Ultimate Lux. Pemicu Lux Mark menguatkan Auto Attack serta Ultimate main Lux.',
    'Harmony menambah ATK dan kerentanan Lux. Stun atau Resilience Break dapat memberi manfaat tambahan.'),
  disc(214003, 'Seed Alike', 'Lux', 5, ['basic', 'skill', 'ultimate', 'buff'],
    'Lux Versatile mengumpulkan Light Particle saat di medan; tumpukan penuh memberi buff Auto Attack kepada main Lux.',
    'Butuh Trekker Lux berperan Versatile dan waktu di medan. Harmony menambah bonus Lux, Skill, serta bonus Mark bersyarat.'),
  disc(214014, 'Sweet Times', 'Terra', 5, ['shield', 'skill', 'buff'],
    'Menaikkan ATK Terra. Memicu Terra Mark memberi main Terra shield yang berskala dari Max HP.',
    'Harmony memberi bonus Terra saat memperoleh shield dan Skill setelah Ultimate Terra jika shield masih aktif.'),
  disc(214037, 'Claw the Claw', 'Terra', 5, ['skill', 'debuff', 'buff'],
    'Menaikkan Terra DMG; target yang Terra Mark-nya dipicu menerima lebih banyak damage Terra.',
    'Harmony mendapat manfaat dari pemulihan HP Terra dan Skill support. Disc ini sendiri tidak memulihkan HP.'),
  skillDisc(213008, 'Tranquil Retreat', 'Ventus'),
  ultimateDisc(213007, 'Emerald Dream', 'Ventus'),
  skillDisc(213004, 'Twin Moon Mischief', 'Ignis'),
  ultimateDisc(213003, "Scorching Night's End", 'Ignis'),
  skillDisc(213010, 'Steam Syndrome', 'Aqua'),
  ultimateDisc(213009, 'Rainy Tune', 'Aqua'),
  skillDisc(213012, 'Starry Night Ode', 'Umbra'),
  ultimateDisc(213011, 'Meow Rhythm', 'Umbra'),
  skillDisc(213006, 'Good Night', 'Lux'),
  ultimateDisc(213005, '★Bam Bam Girl★', 'Lux'),
  skillDisc(213014, "The Knight's Smith", 'Terra'),
  ultimateDisc(213013, 'Leaf Her to Me', 'Terra'),
  elementDisc(212007, 'Brave the Wind', 'Ventus'),
  elementDisc(212005, 'Flare Frenzy', 'Ignis'),
  elementDisc(212008, 'Bubbles', 'Aqua'),
  elementDisc(212009, 'Eclipse', 'Umbra'),
  elementDisc(212006, 'Auspicious Glow', 'Lux'),
  elementDisc(212010, 'Fortitude', 'Terra'),
  disc(211001, 'Crisp Morning', 'Neutral', 3, ['buff'],
    'Menaikkan ATK main Trekker tanpa syarat elemen.', 'Tanpa Harmony. Pilihan umum saat belum memiliki Disc yang lebih sesuai.'),
  disc(211003, 'Indigo Sunset', 'Neutral', 3, ['skill'],
    'Menaikkan Skill DMG main Trekker tanpa syarat elemen.', 'Tanpa Harmony. Fokus efeknya pada main Trekker.'),
  disc(211004, 'Pink Dream', 'Neutral', 3, ['skill'],
    'Menaikkan Skill DMG Trekker pada posisi support.', 'Tanpa Harmony. Pilih jika kontribusi Skill dari support cukup besar.'),
];

export const DATA_META = {
  checkedAt: '2026-09-11',
  label: 'Katalog awal terkurasi',
  note: '24 Trekker dan 30 Disc, bukan daftar lengkap atau tier list meta terbaru. Nama, elemen, role, rarity, serta mekanik merujuk data StellaBase. Tag sinergi, prioritas stat, dan jalur potential merupakan saran kurasi aplikasi. Efek bersyarat dan Harmony tetap memerlukan pemicu, level, serta Note yang sesuai; skor kecocokan bukan simulasi DPS.',
  sources: [
    { label: 'StellaBase · Trekker dan kit', url: `${SOURCE}/trekkers` },
    { label: 'StellaBase · Disc dan efek', url: `${SOURCE}/discs` },
    { label: 'Stella Sora · situs resmi', url: 'https://stellasora.global/' },
  ],
};
